apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: paf-admin
spec:
  storageClassName: upcloud-block-storage-maxiops
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi