apiVersion: apps/v1
kind: Deployment
metadata:
  name: paf-admin-mysql
  labels:
    app: paf-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paf-admin
      tier: mysql
  template:
    metadata:
      labels:
        app: paf-admin
        tier: mysql
    spec:
      restartPolicy: Always
      containers:
      - name: paf-admin-mysql
        image: ${IMAGE}
        args:
          - --max_allowed_packet=1441792
        resources:
          requests:
            cpu: 100m
            memory: 1Gi
        env:
          - name: MYSQL_DATABASE
            valueFrom:
              configMapKeyRef:
                name: paf-admin-mysql
                key: mysql_database
          - name: MYSQL_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: paf-admin-mysql
                key: mysql_password
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: paf-admin-mysql
                key: mysql_root_password
          - name: MYSQL_USER
            valueFrom:
              configMapKeyRef:
                name: paf-admin-mysql
                key: mysql_user
        livenessProbe:
          tcpSocket:
            port: 3306
        ports:
        - containerPort: 3306
          name: paf-admin-mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim